#+TITLE: Emacs configuration
* Personal info

#+BEGIN_SRC emacs-lisp
  (setq user-full-name "Jappie T. Klooster"
        user-mail-address "jappieklooster@hotmail.com"
        calendar-latitude 52.782
        calendar-longitude 6.331
        calendar-location-name "Kerkdijk 2, Ansen")
#+END_SRC

* Remap keys
i3 already uses alt, remap it to windows key
#+BEGIN_SRC emacs-lisp
  (setq x-super-keysym 'meta) 
#+END_SRC
Fucking K is insert enter alright?! I'm so freaking
used to this, and I *NEVER* want to search for the current
word in the manual.

#+BEGIN_SRC emacs-lisp
(define-key evil-normal-state-map (kbd "K") 'newline)
#+END_SRC

** Space menu
Python execute with c x like in rust:
#+BEGIN_SRC emacs-lisp
(spacemacs/set-leader-keys-for-major-mode 'python-mode
  "cx" 'spacemacs/python-execute-file
)
#+END_SRC

I have no idea what the default is but I want to be able to
ctrl click with the keyboad please.
#+BEGIN_SRC emacs-lisp
(spacemacs/set-leader-keys "y" 'ycmd-goto)
#+END_SRC

* Shiny
** Lambda to \lambda
  #+BEGIN_SRC emacs-lisp
  (global-prettify-symbols-mode t)
  #+END_SRC
** line numbers
  #+BEGIN_SRC emacs-lisp
  (add-hook 'prog-mode-hook #'linum-mode)
  (add-hook 'prog-mode-hook #'linum-relative-toggle)
  #+END_SRC
** tab width
#+BEGIN_SRC emacs-lisp
  (setq-default tab-width 4)
#+END_SRC

* YCM
Where is the daemon?
#+BEGIN_SRC emacs-lisp
  (set-variable 'ycmd-server-command '("python" "/home/jappie/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd"))
#+END_SRC

Which languages to complete?
#+BEGIN_SRC emacs-lisp
  (add-hook 'c++-mode-hook 'ycmd-mode)
  (add-hook 'rust-mode-hook 'ycmd-mode)
  (add-hook 'python-mode-hook 'ycmd-mode)
#+END_SRC
* Org mode
** Shiny org
Having + instead of ...
#+BEGIN_SRC emacs-lisp
(setq org-ellipsis " ▼")
#+END_SRC

Syntax highlighting in source blocks while editing
#+BEGIN_SRC emacs-lisp
(setq org-src-fontify-natively t)
#+END_SRC

Use the language's tab major mode
#+BEGIN_SRC emacs-lisp
(setq org-src-tab-acts-natively t)
#+END_SRC

UTF-8 symbols for late shortcuts (such as \alpha).

#+BEGIN_SRC emacs-lisp
(setq org-pretty-entities t)
#+END_SRC

Make latex previews (of complex formulas ie stuff inside []):
#+BEGIN_SRC emacs-lisp
(setq org-startup-with-latex-preview 'latexpreview)
#+END_SRC

** Task management
Org directory
#+BEGIN_SRC emacs-lisp
(setq org-directory "~/org")
(defun org-file-path (filename)
  "Return the absolute address of an org file, given its relative name."
  (concat (file-name-as-directory org-directory) filename))
#+END_SRC

define planning.org as the location to dump todo items in.
#+BEGIN_SRC emacs-lisp
(setq org-index-file (org-file-path "planning.org"))
(setq org-archive-location
      (concat (org-file-path "archive.org") "::* From %s"))
#+END_SRC

anyway more is [[https://github.com/hrs/dotfiles/blob/master/emacs.d/configuration.org][here]]

* Emacs behavior
Don't lock dammit! Its a bad hack to prevent race conditions anyway,
besides the kernel should figure this out. and this way I don't
have to update every gitignore ever.
#+BEGIN_SRC emacs-lisp
  (setq create-lockfiles nil)
#+END_SRC
