# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-31f0cdf0-a13f-410b-94f9-e23436579dd4";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" "noatime"];
    };

  boot.initrd.luks.devices."luks-31f0cdf0-a13f-410b-94f9-e23436579dd4".device = "/dev/disk/by-uuid/31f0cdf0-a13f-410b-94f9-e23436579dd4";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-31f0cdf0-a13f-410b-94f9-e23436579dd4";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" "noatime"];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7290-5734";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/37433f52-ae28-4f72-bca2-436e5bb23529"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
