# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/275ad7d4-1ed6-433a-88bd-aa1d7fb56db4";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."nixenc".device = "/dev/disk/by-uuid/ef300d1d-cf1f-4ba3-82da-d0ce90f831a7";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8096-171C";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/6c5fed09-652b-4a12-8804-2180ab3c0703"; }
    ];

}
