#! /bin/sh
LAPTOP_SCREEN="eDP"
EXTERNAL_OUTPUT="DisplayPort-1"

DAT_FILE="/tmp/monitor_mode_${USER}.dat"

# if we don't have a file, start at zero
if [ ! -f "$DAT_FILE" ] ; then
  monitor_mode="all"

# otherwise read the value from the file
else
  monitor_mode=$(cat "$DAT_FILE")
fi

if [ "$monitor_mode" = "all" ]; then
        monitor_mode="EXTERNAL"
        xrandr --output $LAPTOP_SCREEN --off --output $EXTERNAL_OUTPUT
elif [ $monitor_mode = "EXTERNAL" ]; then
        monitor_mode="MIDDLE"
        xrandr --output $LAPTOP_SCREEN --auto --output $EXTERNAL_OUTPUT
elif [ $monitor_mode = "MIDDLE" ]; then
        monitor_mode="CLONES"
        xrandr --output $LAPTOP_SCREEN --auto \
               --output $EXTERNAL_OUTPUT --auto --same-as $LAPTOP_SCREEN
else
        monitor_mode="all"
        xrandr --output $LAPTOP_SCREEN --auto \
               --output $EXTERNAL_OUTPUT   --auto --above  $LAPTOP_SCREEN
fi

echo "${monitor_mode}"
(i3-nagbar -t warning -m "switching to ${monitor_mode}")&
echo "${monitor_mode}" > "$DAT_FILE"
