#! /bin/sh
EXTERNAL_OUTPUT="DisplayPort-2"
INTERNAL_OUTPUT="DisplayPort-1"
# INTERNAL_OUTPUT="HDMI-A-0"

# if we don't have a file, start at zero
if [ ! -f "/tmp/monitor_mode.dat" ] ; then
  monitor_mode="all"

# otherwise read the value from the file
else
  monitor_mode=`cat /tmp/monitor_mode.dat`
fi

if [ $monitor_mode = "all" ]; then
        monitor_mode="EXTERNAL"
        xrandr --output $INTERNAL_OUTPUT --off --output $EXTERNAL_OUTPUT --mode 3840x2160
elif [ $monitor_mode = "EXTERNAL" ]; then
        monitor_mode="INTERNAL"
        xrandr --output $INTERNAL_OUTPUT --auto --output $EXTERNAL_OUTPUT --off
elif [ $monitor_mode = "INTERNAL" ]; then
        monitor_mode="CLONES"
        xrandr --output $INTERNAL_OUTPUT --auto --output $EXTERNAL_OUTPUT --auto --same-as $INTERNAL_OUTPUT
else
        monitor_mode="all"
        xrandr --output $INTERNAL_OUTPUT --auto --output $EXTERNAL_OUTPUT --mode 3840x2160 --right-of $INTERNAL_OUTPUT
fi

echo "${monitor_mode}"
(i3-nagbar -t warning -m "switching to ${monitor_mode}")&
echo "${monitor_mode}" > /tmp/monitor_mode.dat
chmod 0664 /tmp/monitor_mode.dat
